# netlify.toml
# Comandos para el deploy del sitio en la infraestructura de Netlify.
[build]
  command = "jekyll build"
  publish = "_site"
  environment = { JEKYLL_ENV="production" }

# Redirecci√≥n proxy de contenido estatico alojado en B2 y cacheado por Cloudflare.
[[redirects]]
  from = "/static/*"
  to = "https://f000.backblazeb2.com/file/diegoscl/:splat"
  status = 200
  force = true
  headers = {Cache-Control = "Public, max-age=31536000", X-From = "Netlify CDN"}

# Redirect domain aliases to primary domain
[[redirects]]
  from = "https://belmar.cc/*"
  to = "https://diego.belmar.cc/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://belmar.ws/*"
  to = "https://diego.belmar.cc/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://belmar.me/*"
  to = "https://diego.belmar.cc/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://diego.belmar.ws/*"
  to = "https://diego.belmar.cc/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://diego.belmar.me/*"
  to = "https://diego.belmar.cc/:splat"
  status = 301
  force = true
